const AUTH_INIT = "AUTH_INIT";
const LOGIN_INIT = "LOGIN_INIT";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_ERR = "LOGIN_ERR";
const LOGOUT = "LOGOUT";

export { AUTH_INIT, LOGIN_INIT, LOGIN_SUCCESS, LOGIN_ERR, LOGOUT };
